import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
    {
      name: 'MJ',
      email: 'audwls714@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Hood',
      slug: 'hood',
      category: 'Sport',
      image: '/images/shirt1.jpg',
      price: 1270,
      brand: 'Balenciaga',
      rating: 4.5,
      numReviews: 8,
      countInStock: 12,
      description: 'A popular shirt',
    },
    {
      name: 'Hood',
      slug: 'hood',
      category: 'Sport',
      image: '/images/shirt2.jpg',
      price: 1280,
      brand: 'Balenciaga',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Jean',
      slug: 'jean',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 1000,
      brand: 'Balenciaga',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Wide Pants',
      slug: 'wide-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 390,
      brand: 'Diesel',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Street looking pants',
    },
    {
      name: 'W-Ralle',
      slug: 'w-Ralle',
      category: 'Outer',
      image: '/images/padding1.jpg',
      price: 645,
      brand: 'Diesel',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A comfort pants',
    },
    {
      name: 'Util Pants',
      slug: 'util-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 395,
      brand: 'Diesel',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A comfort pants',
    },
    {
      name: 'Pull-up Pants',
      slug: 'pull-up-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 475,
      brand: 'Rick Owens',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Le grand Chiquito',
      slug: 'le grand Chiquito',
      category: 'Bags',
      image: '/images/bags.jpg',
      price: 675,
      brand: 'JACQUEMUS',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};

export default data;
